### ISSUE TITLE
SPU、SKU的概念都没得？

### ISSUE THREAD

**Issue by li-xunhuan** [newbee-ltd/newbee-mall#13]
？？？？？？？？

**Comment by ZHENFENG13** [comment]
就是个简单的商城 demo，需要这些的话建议你可以去看看其他符合的项目哈，我暂时没时间做。

**Comment by li-xunhuan** [comment]
牛皮，基础概念都莫得都敢卖69……

**Comment by ZHENFENG13** [comment]
这是平台定价，一开始平台定价是99。

另外，这项目所有代码开源的，又不是不买文档不让你用，就别一直阴阳怪气的了。当然，也希望你早日开发出你想要的项目哈。

**Comment by li-xunhuan** [comment]
我已经搞完了啊，只是想看看配套代码是啥样的而已。并没有阴阳怪气。只是觉得和标题相差甚远而已~

**Comment by ZHENFENG13** [comment]
OK，回头给你点star
