### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by WXB2010** [newbee-ltd/newbee-mall#18]
大佬您好，后台商品管理怎么上传图片的呢，没看到有图片上传

**Comment by WXB2010** [comment]
大佬，图片上传知道了，就是有个问题，我浏览商品的时候，查看商品详情就让我登录，我想着是购买或者加入购物车的时候再登录，然后我把商城页面登录拦截那里的代码：.addPathPatterns("/goods/detail/**")删掉了，好像不可以呢，点击购买和加入购物车就没反应了

**Comment by ZHENFENG13** [comment]
#19
