### ISSUE TITLE
register is faied

### ISSUE THREAD

**Issue by YueYFei** [newbee-ltd/newbee-mall#2]
注册的时候出现未知异常请联系管理员,应该怎么解决呀？谢谢你的回答，还有upload应该直接放在resource下边吗

**Comment by ZHENFENG13** [comment]
根据这个描述，感觉是没连上数据库，具体的问题从你的描述中不太好定位出来，要不加一下 QQ 群吧，群号：796794009

**Comment by YueYFei** [comment]
好的，多谢了哈哈
