### ISSUE TITLE
newbee-mall项目的mybatis plus版本 添加了秒杀专区、优惠卷领取、 支付宝沙箱支付以及后台添搜索功能

### ISSUE THREAD

**Issue by wayn111** [newbee-ltd/newbee-mall#23]
地址：https://github.com/wayn111/newbee-mall

**Comment by Hao-000** [comment]
老哥6666

**Comment by newbee-mall** [comment]
[newbee-mall-plus](https://github.com/newbee-ltd/newbee-mall-plus) 已开源。
