### ISSUE TITLE
suggest use lombok

### ISSUE THREAD

**Issue by li-liang-jie** [newbee-ltd/newbee-mall#25]
suggest use lombok

**Comment by ZHENFENG13** [comment]
OK

**Comment by newbee-mall** [comment]
![](https://github.com/newbee-ltd/newbee-mall-api/raw/master/static-files/newbee-mall.png)
新蜂商城前后端分离版本：

- [后端接口 newbee-mall-api](https://github.com/newbee-ltd/newbee-mall-api)
- [前端页面 newbee-mall-vue-app](https://github.com/newbee-ltd/newbee-mall-vue-app)
