### ISSUE TITLE
这种接近纯收费意向的项目放在github上?

### ISSUE THREAD

**Issue by alexli0707** [newbee-ltd/newbee-mall#27]
君子爱财,取之有道. 拉自己的qq群玩玩就好了

**Comment by ZHENFENG13** [comment]
所有代码、所有资源文件、所有数据库文件等等内容都是开源的，所以为什么不能放在 GitHub 上？所有代码和资源可以直接下载使用，没有任何藏着掖着不公开的行为。
掘金小册[《Spring Boot 大型线上商城项目实战教程》](https://juejin.im/book/5da2f9d4f265da5b81794d48?referrer=59199e22a22b9d0058279886)只是一个衍生作品而已，小册中使用的讲解代码也与开源的代码基本一致，**想要学习和使用这个开源的商城项目并不一定要购买这本小册**，是否购买小册完全取决于自己是否有需求，相信大家的判断即可。

**Comment by LBC000** [comment]
> 所有代码、所有资源文件、所有数据库文件等等内容都是开源的，所以为什么不能放在 GitHub 上？所有代码和资源可以直接下载使用，没有任何藏着掖着不公开的行为。 掘金小册[《Spring Boot 大型线上商城项目实战教程》](https://juejin.im/book/5da2f9d4f265da5b81794d48?referrer=59199e22a22b9d0058279886)只是一个衍生作品而已，小册中使用的讲解代码也与开源的代码基本一致，**想要学习和使用这个开源的商城项目并不一定要购买这本小册**，是否购买小册完全取决于自己是否有需求，相信大家的判断即可。

我看到软著还以为不能商用, 听到作者大大这么说我就放心了
