### ISSUE TITLE
【校招社招】这套商城跟淘宝天猫有什么差别，不好奇吗？

### ISSUE THREAD

**Issue by Nerom** [newbee-ltd/newbee-mall#29]
阿里直招，社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会

公司/团队介绍
我们是阿里巴巴集团新零售技术旗下供应链技术国际化团队，我们致力于通过世界一流的全球化技术服务来自全球10亿+的海外消费者，为全球消费者带去极致的购物体验，让买全球卖全球的使命落地成为普惠全球的显示图景。我们服务的业务实体有 lazada、AliExpress、天猫海外、Daraz、Trendyol等平台。

联系方式
邮箱： liuzhu.wlz#alibaba-inc.com

**Comment by newbee-mall** [comment]
？？？

**Comment by Nerom** [comment]
> 喵喵喵？？？

借大佬宝地一用，招人太难了，大佬也可以帮忙找找人，社招内推成功入职有奖金的

**Comment by molixiu** [comment]
> 
> 
> > 喵喵喵？？？
> 
> 借大佬宝地一用，招人太难了，大佬也可以帮忙找找人，社招内推成功入职有奖金的

阿里太难了，秋招我测评后就没信了。。。。。。

**Comment by PPeony** [comment]
插个眼，等我学完了我就去扔简历

**Comment by TheShadow629** [comment]
？？？

**Comment by BelovedStocky** [comment]
简历投过了，一点消息都没有了不是

**Comment by Nerom** [comment]
> 简历投过了，一点消息都没有了不是

老哥是发到邮箱了吗？没看到有新简历呢。。

**Comment by BelovedStocky** [comment]
我之前其他渠道投过阿里的简历，够不到门槛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nerom"<notifications@github.com&gt;; 
发送时间: 2020年9月21日(星期一) 中午11:27
收件人: "newbee-ltd/newbee-mall"<newbee-mall@noreply.github.com&gt;; 
抄送: "澜翎雨忆"<2313753427@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [newbee-ltd/newbee-mall] 【校招社招】这套商城跟淘宝天猫有什么差别，不好奇吗？ (#29)





  
简历投过了，一点消息都没有了不是
  
老哥是发到邮箱了吗？没看到有新简历呢。。
