### ISSUE TITLE
Api文档有吗

### ISSUE THREAD

**Issue by leielyq** [newbee-ltd/newbee-mall#31]

**Comment by ZHENFENG13** [comment]
新版本会有的，正在整理中。

**Comment by leielyq** [comment]
啊，有新版吗？那小册我刚买唉

**Comment by ZHENFENG13** [comment]
有的，Spring Boot + Vue 版本的

**Comment by newbee-mall** [comment]
![](https://github.com/newbee-ltd/newbee-mall-api/raw/master/static-files/newbee-mall.png)
新蜂商城前后端分离版本：

- [后端接口 newbee-mall-api](https://github.com/newbee-ltd/newbee-mall-api)
- [前端页面 newbee-mall-vue-app](https://github.com/newbee-ltd/newbee-mall-vue-app)

**Comment by leielyq** [comment]
@newbee-mall 404啦~私有？

**Comment by newbee-mall** [comment]
有点问题，调整一下，放心，会开源的

**Comment by leielyq** [comment]
@newbee-mall 好的

**Comment by leielyq** [comment]
nice

**Comment by fanyaow** [comment]
文档连接,能放到github不,连接都打不开

**Comment by newbee-mall** [comment]
> 文档连接,能放到github不,连接都打不开

什么链接？
