### ISSUE TITLE
界面显示问题

### ISSUE THREAD

**Issue by vaeal** [newbee-ltd/newbee-mall#4]
作者你好像没有提供商品图片的文件夹，导致不能显示商品的图片。或者还是我自己哪里出错了。
![image](https://user-images.githubusercontent.com/45780395/69563181-8f0dd100-0feb-11ea-97c5-16fcd70fe362.png)
`

**Comment by ZHENFENG13** [comment]
你自己的设置问题，可以加群讨论。
