### ISSUE TITLE
测试账号密码是啥啊

### ISSUE THREAD

**Issue by wen521** [newbee-ltd/newbee-mall#40]

**Comment by human2312** [comment]
admin / 123456

**Comment by chihiro2014** [comment]
> admin / 123456

验证码一直报错，输入正确，也被判错

**Comment by ZHENFENG13** [comment]
> > admin / 123456
> 
> 验证码一直报错，输入正确，也被判错

QQ群加一下，791509631，然后把详细的问题截图发来我看一下。
