### ISSUE TITLE
我下载了你最新版本的代码，但是启动项目以后，验证码怎么输入都是错误的，这个问题怎么解决啊

### ISSUE THREAD

**Issue by LIUhong123456** [newbee-ltd/newbee-mall#44]
![X1O0RF%YT11NCO(@EAANFSV](https://user-images.githubusercontent.com/77084683/103842165-36ef3c80-50d0-11eb-96f4-c3372c8208ee.png)

**Comment by newbee-mall** [comment]
输入小写的即可，我改一下代码吧。
