### ISSUE TITLE
建议在协议上增加附加条件，比如只允许学习使用，任何商用行为需要获得授权。

### ISSUE THREAD

**Issue by hello2dj** [newbee-ltd/newbee-mall#48]
[如何看待开源软件的知识产权问题](https://patent.bbscloud.com/info/4103cb04aaac4b1fb6c3e9d7d22ed53b)
这样后续任何使用该项目的人都可以清晰的了解到使用范围，而不是使用 GPL 协议加软件著作权，还得仔细看看他俩的内容。
举个例子：如果我使用该软件并且修改了还售卖服务，我只要开源就好了（根据 GPL），不需要获得原作者的授权。那对于软件著作权来说我需要获得原作者的授权么？没有仔细了解，不清楚。

**Comment by ZHENFENG13** [comment]
开源项目正常使用没事的，别删原作者的版权信息然后说是自己的原创项目，这个和开源协议已经没关系了，任何协议也不允许这么干。至于软件著作权也是为了保护自己，而不是为了限制用户。

**Comment by hello2dj** [comment]
既然和协议无关联了，何苦从 MIT 改成 GPL 呢？创作很辛苦，只是个人认为写清楚会方便你我他
