### ISSUE TITLE
技术问答

### ISSUE THREAD

**Issue by mgljava** [newbee-ltd/newbee-mall#5]
大佬后期是否考虑引入Redis、MongoDB、ES等技术

**Comment by newbee-mall** [comment]
Redis 和 Elastic Search 在计划内。

**Comment by mgljava** [comment]
> Redis 和 Elastic Search 在计划内。

可以参与到其中来么

**Comment by ZHENFENG13** [comment]
可以啊，但是这些技术栈不会在这个项目里使用，[newbee-mall](https://github.com/newbee-ltd/newbee-mall) 这个仓库主要考虑到初学者和经验不足的朋友，所以不会在项目里放太多中间件，我会另外新建一个仓库来做这些中间件的整合，相当于一个进阶版本，有兴趣的话你可以联系我哈。

**Comment by JackZhangYu** [comment]
我在一个项目里已经实现课es和redis。可以参与进去吗

**Comment by ZHENFENG13** [comment]
现在在外面，你可以发邮件给我，我回去和你联系

**Comment by chenmg2020** [comment]
适合学习的好项目呀。感谢前辈
