### ISSUE TITLE
用户信息更新存在横向越权

### ISSUE THREAD

**Issue by BACMiao** [newbee-ltd/newbee-mall#76]
您好，我们对您的项目源码进行分析，发现在用户信息更新模块内存在的横向越权的情况，可以通过修改请求中的userId使得不需要密码验证的情况下直接登陆别的用户。
## 相关版本：
1f2c2dfy 提交版本（10月28日）

## 横向越权行为源码位置：
`ltd.newbee.mall.controller.mall.PersonalController`下的`updateInfo`函数
![image](https://user-images.githubusercontent.com/15136865/198541194-f31797d0-e67a-4236-8f75-18c53a83e251.png)

`ltd.newbee.mall.service.impl.NewBeeMallUserServiceImpl`下的`updateUserInfo`函数
![image](https://user-images.githubusercontent.com/15136865/198541286-fac8b447-5b62-4e16-990e-91e41a52b50c.png)

**由于mallUser.getUserId是用户可控的，并且逻辑上缺少校验机制，因此在红色方框标记的地方存在横向越权的行为，可以通过修改用户的Id获取直接使用别的用户登陆。**

## 横向越权漏洞复现：
**使用工具为BurpSuite**

1. 登陆账户：**测试用户3**，该用户的订单为空：
![image](https://user-images.githubusercontent.com/15136865/198542081-23c9de28-9987-4999-8958-2053910b4331.png)

![image](https://user-images.githubusercontent.com/15136865/198542127-2faaad9b-27e3-44f4-a55f-7b08fd81a972.png)

2. 修改个人信息并提交：
![image](https://user-images.githubusercontent.com/15136865/198542270-50de738e-0501-4899-ade2-02cbba00892d.png)

3. 使用BurpSuite拦截该请求并篡改userId后发送该请求：
![image](https://user-images.githubusercontent.com/15136865/198542427-7e82ca13-f0b1-4b13-8771-350865249902.png)

4. 现在用户：**十三**，不需要用户登陆验证，直接可以冒用别的用户身份和修改相关信息和订单：
![image](https://user-images.githubusercontent.com/15136865/198542678-4b60e7c3-8490-42a9-b002-bc6ed74614ad.png)
![image](https://user-images.githubusercontent.com/15136865/198542707-8ee37b50-0f64-4602-98e3-ed797dedd09e.png)

**Comment by ZHENFENG13** [comment]
收到，近期会处理掉。

**Comment by dtwin88** [comment]
> 不是，你真处理了吗，这不是还在吗？？？

处理了，师傅你在先知文章上分析的有问题，这里已经没有漏洞了，是服务端响应欺骗，原来有水平越权是因为userFromDB在if语句中重新赋值，现在的代码没有重新赋值，就是根据session来判定用户的，无法越权修改别人信息。

**Comment by ez-lbz** [comment]
> > 不是，你真处理了吗，这不是还在吗？？？
> 
> 处理了，师傅你在先知文章上分析的有问题，这里已经没有漏洞了，是服务端响应欺骗，原来有水平越权是因为userFromDB在if语句中重新赋值，现在的代码没有重新赋值，就是根据session来判定用户的，无法越权修改别人信息。

师傅您说的对，我确实分析的有问题，这里是修改的从Session拿取的userFromDB
