### ISSUE TITLE
几个潜在漏洞提醒

### ISSUE THREAD

**Issue by xiaozhicai** [newbee-ltd/newbee-mall#8]
AdminLoginInterceptor存在绕过风险，uri.startsWith("/admin"）可以用../绕过，建议对uri进行归一化处理后再进行操作

admin/upload/file接口，任意文件上传+跨目录上传，结合上AdminLoginInterceptor的绕过很容易被种马

**Comment by ZHENFENG13** [comment]
好的，谢谢提醒。
