### ISSUE TITLE
XSS attacks exist in the new product launch configuration in the background

### ISSUE THREAD

**Issue by superd1ng** [newbee-ltd/newbee-mall#84]
在后台选择新平上线配置，输入_`"<img src=x onerror=alert(1)>"`_报错

Select Xinping online configuration in the background, enter _`"<img src=x onerror=alert(1)>"`_ to report an error
 
![image](https://github.com/newbee-ltd/newbee-mall/assets/78067010/b59afa0f-30f3-4648-8645-e76b63794627)

输入合法字符 例如1234
抓包修改即可
Enter legal characters such as 1234
You can modify the packet capture
![image](https://github.com/newbee-ltd/newbee-mall/assets/78067010/72375a29-366c-41ca-9409-5148d2ca5f8a)

 
将符合规则的configName修改为<img src=x oneror=alert(1)>即可

Modify the configName that meets the rules to <img src=x oneror=alert(1)>
![image](https://github.com/newbee-ltd/newbee-mall/assets/78067010/84d43ff2-219c-48ac-ba85-571ddfb4bd98)

 
经过测试 后台基本上商品的修改都是经过接口/admin/indexConfigs/update
源码分析：

After testing, basically the modification of the product in the background is through the interface /admin/indexConfigs/update
Source code analysis:
 
![image](https://github.com/newbee-ltd/newbee-mall/assets/78067010/41692b06-0b8e-4d2b-afa6-ed0689924c88)

可以看到update只是对参数 configId，configType，configName，configRank是否为空或者字符串

It can be seen that the update is only for the parameters configId, configType, configName, configRank whether it is empty or a string
 
![image](https://github.com/newbee-ltd/newbee-mall/assets/78067010/8fe85f88-5848-4c4e-8d71-982e712912b6)
![image](https://github.com/newbee-ltd/newbee-mall/assets/78067010/2dbbe133-e1c8-4d04-8424-917879c512ca)

 
这里的hasText方法 也就是 判断输入的是字符串
之后调用updateIndexConfig方法

The hasText method here is to judge that the input is a string
Then call the updateIndexConfig method
![image](https://github.com/newbee-ltd/newbee-mall/assets/78067010/c5a34943-0aef-47cf-9fb7-ad066848c940)

 
这里就是判断商品是否在数据库中存在 ，之后调用updateByPrimaryKeySelective方法修改
没有对XSS进行过滤 导致存在XSS

Here is to judge whether the product exists in the database, and then call the updateByPrimaryKeySelective method to modify
XSS is not filtered, resulting in XSS

**Comment by ZHENFENG13** [comment]
#64
