### ISSUE TITLE
sql文件报错了，作者大大

### ISSUE THREAD

**Issue by foehsac** [newbee-ltd/newbee-mall#85]
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'##\''COMMENT'鐐瑰嚮鍚庣殑璺宠浆鍦板潃(榛樿涓嶈烦杞?',
  ' at line 3

**Comment by ZHENFENG13** [comment]
这是乱码了，你看看数据库编码设置，还有数据库版本之类的，这个和我提供的文件不搭噶的。
