### ISSUE TITLE
页面错误

### ISSUE THREAD

**Issue by 380281626** [newbee-ltd/newbee-mall#91]
商城页面错误，没有正常显示。
![黑屏](https://github.com/newbee-ltd/newbee-mall/assets/167297248/254f6309-45c6-4215-9472-1a6f6cf072b9)

**Comment by ZHENFENG13** [comment]
分类数据问题，你加个几条。

**Comment by 380281626** [comment]
你好，

有段时间没上了，商城后台管理员账号密码是多少？


Thanks and best regards/诚挚的问候
----------------------------------------------------------------
Chen Yuancheng/陈远成
Phone/电话: 186-4033-6397
________________________________
